### PR TITLE
envoy configuration comments

### PR DESCRIPTION
**Pull request by cpt-redbeard**
Adding comments for non-conventional naming conventions and modifications options.

### CODE REVIEW

**Comment by KoppulaRajender** [comment]
Hi @cpt-redbeard, You have been raised the changes on the older branch (master) the current default branch is 5.3 and the latest is 6.0 branch respectively, and from 5.3 we are not supporting platform-specific ( deployments/orchestrators/ ) manifests, we included all platforms manifests at a single place ( deployments/orchestrators/kubernetes/manifests/ ).

added the requested comments changes to 5.3 (#142 )and 6.0 (#141 )

Closing your PR. Let us know if you have any further queries.

**Comment by rshmiel** [comment]
@cpt-redbeard please review Raj PRs: #142 #141

**Comment by cpt-redbeard** [comment]
> @cpt-redbeard please review Raj PRs: #142 #141

reviewed them and looks good. Plus it looks like they were already merged.

**Comment by rshmiel** [comment]
yes the PRs are merged. just informed you because we closed yours. thanks

**Pull request closed without merging**
