### PR TITLE
6.0| Fix rawk8s 1.19.2 mutation certs

### PR DESCRIPTION
**Pull request by SaiMandalo**
Updated certificates generation needed for communicating kube-api
server. added subjectAltName to the server.conf file to make it work for
kubernetes 1.19.2

### CODE REVIEW

**Comment by SaiMandalo** [comment]
@xB-2048 @rshmiel

**Comment by rshmiel** [comment]
@SaiMandalo we need this one to be done on HELM 6.0

**Comment by SaiMandalo** [comment]
> @SaiMandalo we need this one to be done on HELM 6.0

@rshmiel yes, changes are already merged to helm 6.0 with https://github.com/aquasecurity/aqua-helm/pull/160 PR

**Comment by kenmccann** [comment]
> > @SaiMandalo we need this one to be done on HELM 6.0
> 
> @rshmiel yes, changes are already merged to helm 6.0 with [aquasecurity/aqua-helm#160](https://github.com/aquasecurity/aqua-helm/pull/160) PR

@SaiMandalo Is that the same thing?  This PR modifies the altname in the KE cert.  The PR you linked to parameterizes the namespace name in the Envoy config so it can connect to the Gateway service based on the chosen namespace name.

That raises another concern that this PR hard-codes "aqua" in the alt subject name.

**Comment by SaiMandalo** [comment]
> > > @SaiMandalo we need this one to be done on HELM 6.0
> > 
> > 
> > @rshmiel yes, changes are already merged to helm 6.0 with [aquasecurity/aqua-helm#160](https://github.com/aquasecurity/aqua-helm/pull/160) PR
> 
> @SaiMandalo Is that the same thing? This PR modifies the altname in the KE cert. The PR you linked to parameterizes the namespace name in the Envoy config so it can connect to the Gateway service based on the chosen namespace name.
> 
> That raises another concern that this PR hard-codes "aqua" in the alt subject name.

@kenmccann As of now KE is not supported to run in non-aqua namespaces. It is planned in next release to remove the namespace dependency.
with 6.0 release the hard-coded 'aqua' will not make any issue.
Let me know if i'm  missing any

**Pull request merged**
