### PR TITLE
updating advance config for gateway 6.0 (slk-30464)

### PR DESCRIPTION
**Pull request by KoppulaRajender**

### CODE REVIEW

**Comment by guyyakir** [comment]
@rshmiel @KoppulaRajender  is this change going to be in 5.3 also ?

**Comment by guyyakir** [comment]
also i suggest not to change the envoy files names since aquactl rely on them. instead add orchestrators/kubernetes/manifests/aqua_csp_007_networking/envoy/0001_server_gateway_service-envoy.yaml

(instead of 001...)

WDYT @rshmiel @KoppulaRajender

**Comment by KoppulaRajender** [comment]
> @rshmiel @KoppulaRajender is this change going to be in 5.3 also ?

No, only going to 6.0

**Comment by guyyakir** [comment]
@rshmiel we need to see if it's possible to support both 5.3 and 6.0 were the GW are located in different files

**Comment by KoppulaRajender** [comment]
opened https://github.com/aquasecurity/deployments/pull/110 due to merge conflict

**Pull request closed without merging**
